### ISSUE TITLE
X calibration 

### ISSUE THREAD

**Issue by khoroshyy** [fujii-team/sif_reader#3]
Hi 
Can I ask you to add X calibration to this reader.
I will try to work it out myself have no clue how long it will take me. but you may do it faster, as I will need to learn what is your code doing.
I am attaching two files. One is a single line spectrum. X calibrated in wavelength nanometers. 
Calibration information looks like below. polynom coefficients in the first line:  
-----------------------------------------------
# here is the part where X wavelength calibration stored
# 405.184510498139 0.0486615559015733 -3.17780657750795e-07 -1.1864020166803e-10
# 0 1 0 0
# 0 1 0 0
# 422
# 13
# 13
# 1
# 10
# Wavelength6 
---------------------------------------------------

And can be calculated like:
--------------------------------------------------
from pylab import *
cal_coeffitients =  array([405.184510498139,
                          0.0486615559015733,
                          -3.17780657750795e-07,
                          -1.1864020166803e-10])
polinom = poly1d(flipud(cal_coeffitients))
wavelength = polinom(arange(1,1025))
 -------------------------------------------------
Another file has data from step and scan measurement, and wavelength calibration for each frame is stored in the comment section on the top of sif file.
Thank you.
Petro

[nd_lum_image_no_glue.zip](https://github.com/fujii-team/sif_reader/files/1303095/nd_lum_image_no_glue.zip)
[raman1.zip](https://github.com/fujii-team/sif_reader/files/1303096/raman1.zip)

**Comment by fujiisoup** [comment]
Hi @khoroshyy 

Thanks for raising an issue. 
I would like to try that, but as I have not used X-calibrated data, it will take some days.

I have two requests.
1. Can I have an *answer* data for your sif file?
If you could attach it as a text file, it would be useful to make sure the result is correct.

2. Do you have any request for the API?
Currently, we do have `sif_reader.np_open` and `sif_reader.xr_open` methods.
The API for `sif_reader.xr_open` is apparent as `xr.DataArray` can store coordinate values.
For `sif_reader.np_open`, we currently return a `np.ndarray` and an `OrderedDict`.
My inclination is to store the calibrated data in `OrderedDict` with a key like `X-coordinate`.

**Comment by khoroshyy** [comment]
Hi,
It is fine with me to store it in OrderedDict.
What software do you use? If you use Solis software, it shall read my sif
files without problem, including calibration. If not I can upload a txt
version a bit later.

Also, I have collected a couple of different readers which never worked
with my files. Some of them might be useful in tracking meaning of
different parts of the SIfFile format. If you are interested I can drop
them to you email. Some of them are probably already known to you.

Regards.
Petro



______________________________
Petro Khoroshyy

**Comment by khoroshyy** [comment]
One more thing,
X calibration can be of 3 different types:
Pixel number
Wavelength in nano meters
Raman shift in (1/cm)
I attach one more sif file calibrated in Raman 
And txt versions of each file.
[raman1_wavenumber.zip](https://github.com/fujii-team/sif_reader/files/1303457/raman1_wavenumber.zip)
Best regards and thank you.

**Comment by fujiisoup** [comment]
@khoroshyy I am struggling to read raman1.sif.
(nd_lum_image_no_glue.zip seems OK.)

I am not sure how X-calibrated data is stored inside the .sif file.
How did you input the calibration data? Your spectrograph automatically attaches it?

**Comment by khoroshyy** [comment]
Hi,
Indeed , reading raman1.sif with python script produces garbage. The difference between two files is that one is image and another is single raw. Probably this causes the difference. I will make a multi line calibrated data image to see if it is readable. Then I can use it before figuring out what is the problem.
Calibration is added by AndorSolis software based on data read from spectrograph.
Calibration data for nd_lum_image_no_glue.sif are stored on the top of the file.
I am attaching a print screen of the file with its data.
![nd_calibration_data](https://user-images.githubusercontent.com/1734704/30532336-0cd3abd6-9c54-11e7-9440-6e6faa8b3168.PNG)
Calibration is not stored as values of X but as polynomial coefficients in lines 8-17.
This is one case, it is slightly different if there is only one frame.
 
![one_frame_calibration](https://user-images.githubusercontent.com/1734704/30532473-c13e888e-9c54-11e7-9dc3-fd60aad54517.PNG)
Then it is in line 34 in the picture above.
For example if coefficients are:
405.184510498139 0.0486615559015733 -3.17780657750795e-07 -1.1864020166803e-10
X values (wavelength in nanometers )are calculated in following way:
wavelength =  405.184510498139 +0.0486615559015733*X - 3.17780657750795e-07*X^2 -1.1864020166803e-10*X^3
Where X is pixel number 
Raman shift calibration is recalculated from wavelength calibration each time using excitation wavelengh, on picture above it is in line 37 (422 nm). But since it is secondary we can leave Raman calibration out for now.
 I also wanted to ask what type and version of Andor software are you using? I use Andor Solis 64 bit. ver 4.28.30050. What is yours?

**Comment by fujiisoup** [comment]
@khoroshyy 
Thanks for the information.
Try this (#4) branch.
I think now it works.

Note that `raman1_wavenumber.sif` contains the same calibration coefficients and seems to convert in Andor app.

**Comment by fujiisoup** [comment]
Another note.
Calibration coefficients are stored in `info['Calibration_data']` or info['Calibration_data_for_frame_1'].

The calibration vector can be quickly extracted the newly added function
`sif_reader.utils.extract_calibration(info)`

I also recommend using [`xarray`](http://xarray.pydata.org), 
which is a library to handle multi-dimensional data with coordinates.

In `sif_reader`, we have `sif_reader.xr_open`, which returns a single `xarray.DataArray` object with the coordinates (such as time and calibration) embedded.

**Comment by khoroshyy** [comment]
Thanks,

So far it was working.
